=== rad55RUS/CoolStoreProject_Coursework/Data/Schemas/BonusCards_Schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="BonusCards">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BonusCard" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Number" type="xs:string"/>
							<xs:element name="Bonuses" type="xs:int"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== rad55RUS/CoolStoreProject_Coursework/Data/BonusCards.xml
<?xml version="1.0" encoding="utf-8" ?>
<BonusCards
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Schemas\BonusCards_Schema.xsd">
	<BonusCard>
		<!--Some client data-->
		<Number>3131-4141-5353-7474</Number>
		<Bonuses>424</Bonuses>
	</BonusCard>
	<BonusCard>
		<!--Some client data-->
		<Number>4387-3458-3874-3412</Number>
		<Bonuses>100</Bonuses>
	</BonusCard>
	<BonusCard>
		<!--Some client data-->
		<Number>6841-5134-7913-5408</Number>
		<Bonuses>0</Bonuses>
	</BonusCard>
	<BonusCard>
		<!--Some client data-->
		<Number>8463-8452-1852-3542</Number>
		<Bonuses>15405</Bonuses>
	</BonusCard>
</BonusCards>
