=== rad55RUS/CoolStoreProject_Coursework/Data/Schemas/Users_Schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Users">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="User" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Cash" type="xs:double"/>
							<xs:element name="CardMoney" type="xs:double"/>
							<xs:element name="BonusCard" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== rad55RUS/CoolStoreProject_Coursework/Data/Users.xml
<?xml version="1.0" encoding="utf-8" ?>
<Users
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Schemas\Users_Schema.xsd">
  <User>
    <Cash>490</Cash>
    <CardMoney>0</CardMoney>
    <BonusCard>3131-4141-5353-7474</BonusCard>
  </User>
  <User>
    <Cash>0</Cash>
    <CardMoney>8241</CardMoney>
    <BonusCard>4387-3458-3874-3412</BonusCard>
  </User>
  <User>
    <Cash>0</Cash>
    <CardMoney>0</CardMoney>
    <BonusCard>6841-5134-7913-5408</BonusCard>
  </User>
  <User>
    <Cash>668</Cash>
    <CardMoney>542</CardMoney>
    <BonusCard>8463-8452-1852-3542</BonusCard>
  </User>
</Users>
